name: Release

on:
  push:
    branches:
      - master

jobs:
  npm:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: Build release scripts
        uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: build

      - name: Release
        uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: release
          affected: false
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master to develop
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch
          git checkout develop
          git pull
          git merge --no-ff master -m "Auto-merge master back to develop"
          git push
