name: Release

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - develop
      - feat/test

jobs:
  npm:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch latest base branch
        run: git fetch origin master

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.5
        with:
          nx-key: build

      - name: Build release scripts
        uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: build
          projects: builders

      - name: Release
        uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: release
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
